### ISSUE TITLE
Pipeline stops execution with ceph 503 error, even when use_ceph is False

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/meteor#32]
**Describe the bug**
Elyra pipeline in tutorial errors out due to code 503 from ceph endpoint, even though the environment variable `TUTORIAL_USE_CEPH` is set to "0". Is this expected behavior?

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud
2. Spawn Elyra tutorial image
3. Clone your fork of Elyra tutorial repo
3. Install runtime images as described [here](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e967491ebb77f83a6a5ba360b5f6516f827080f9/docs/source/create-ai-pipeline.md#add-runtime-images-using-ui) (but using tag `v0.9.0` instead of `v0.5.0`).
4. Create runtime as described [here](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e967491ebb77f83a6a5ba360b5f6516f827080f9/docs/source/create-ai-pipeline.md#create-runtime-to-be-used-in-kubeflow-pipeline-using-ui).
5. Set the `TUTORIAL_USE_CEPH` env var to `"0"` (see screenshot 1)
6. Save and run pipeline
7. Open KF pipelines UI and see 503 errors in [pod logs](http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/pipeline/#/runs/details/f0004ad2-a293-4602-bd97-0d76efe3a489) (see screenshot 2)

**Expected behavior**
Pipeline runs without errors

**Screenshots**
![Screenshot from 2021-07-02 16-53-01](https://user-images.githubusercontent.com/15005500/124327501-04417080-db56-11eb-906f-961677c76a89.png)

![Screenshot from 2021-07-02 16-55-54](https://user-images.githubusercontent.com/15005500/124327773-6a2df800-db56-11eb-9494-57156c90ec4a.png)

Related to #16

**Comment by pacospace** [comment]
this can be closed as it was solved by @MichaelClifford: https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/167/files, the new image needs to be added to Operate First.

**Comment by chauhankaranraj** [comment]
> this might be solved by @MichaelClifford: https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/167/files, the new image is available on Operate First as content image, like ocp-ci-analysis

Hmm I ran the pipeline using the Elyra AIDevSecOps Tutorial image on operate-first JH, and using the operate-first "public" [s3 storage](https://github.com/operate-first/support/issues/165#issuecomment-810337239), and I still see this. Did I misconfigure something?

**Comment by chauhankaranraj** [comment]
Update: I had configured the runtime to use endpoint `https://s3-openshift-storage.apps.zero.massopen.cloud`, but changing it to `http://s3.openshift-storage.svc/` fixed the 503 error. Closing this issue.
